---
-  hosts: all
   become: true
   vars:
     motd:
       - Ansible managed node by pastrana
   vars_prompt:
       - name: username
         prompt: Input username
         private: false

       - name: uid
         prompt: Input ID
         private: false

   tasks:
   -  name: Installs latest python3 and pip3
      package:
        name:
         - python3
         - python3-pip
        state: latest
        update_cache: yes

   - name: Installs Java open-jdk in Ubuntu
     apt:
       name:
       - openjdk-17-jdk
       state: latest
       update_cache: yes
     when: ansible_distribution == "Ubuntu"

   - name: Installs Java open-jdk in CentOS
     yum:
       name:
       - java-11-openjdk
       state: latest
       update_cache: yes
     when: ansible_distribution == "CentOS"

   -  name: Banner MOTD
      ansible.builtin.debug:
       msg:
         -  "{{ motd }}"

   - name: Create a User
     ansible.builtin.user:
       name: "{{ username }}"
       comment: New User
       uid: "{{ uid }}"
       createhome: yes
       home: /home/"{{ username }}"
       shell: /bin/bash
